#!/bin/bash

JS_COMPRESSION_OPTS="dead-code=false,unsafe=false,unused=false"

# Output files
HTML_OUTPUT="../index.html"
CSS_OUTPUT="../styles.css"
JS_OUTPUT="../scripts.js"

check_lessc() {
    if type lessc &> /dev/null; then
        LESSC=lessc
    else
        if [ ! -f node_modules/.bin/lessc ]; then
            echo "Installing less"
            npm install less
        fi
        LESSC=node_modules/.bin/lessc
    fi
}

check_uglifyjs2() {
    if [ ! -f node_modules/.bin/uglifyjs2 ]; then
        echo "Installing uglify-js2"
        npm install uglify-js2
    fi
    UGLIFYJS2=node_modules/.bin/uglifyjs2
}


check_uglifycss() {
    if [ ! -f node_modules/.bin/uglifycss ]; then
        echo "Installing uglifycss"
        npm install uglifycss
    fi
    UGLIFYCSS=node_modules/.bin/uglifycss
}

# I should've done this with a Makefile

if [ ! -f "$HTML_OUTPUT" -o ../bibliography.js -nt "$HTML_OUTPUT" -o $(find ../doc/ -name '*.txt' -newer "$HTML_OUTPUT"  2>/dev/null | wc -l) -gt 0 ]; then
    node lib/main.js
    echo "Generated HTML"
fi

if [ ! -f "$CSS_OUTPUT" -o ! -f ../css/styles.css -o ../css/styles.less -nt "$CSS_OUTPUT" ]; then
    check_lessc
    $LESSC -x ../css/styles.less > ../css/styles.css
    echo "Generated styles.css"
fi

if [ ! -f "$CSS_OUTPUT" -o $(find ../css/ -name '*.css' -newer "$CSS_OUTPUT" 2>/dev/null | wc -l) -gt 0 ]; then
    check_uglifycss
    $UGLIFYCSS ../css/{styles,keys,codemirror}.css > "$CSS_OUTPUT"
    echo "Compressed CSS"
fi

if [ ! -f "$JS_OUTPUT" -o $(find ../js/ -name '*.js' -newer "$JS_OUTPUT"  2>/dev/null | wc -l) -gt 0 ]; then
    check_uglifyjs2
    $UGLIFYJS2 ../js/{codemirror,javascript,clike,scheme,parse-js,process,formatter}.js -o "$JS_OUTPUT" -c $JS_COMPRESSION_OPTS
    echo "Compressed JS"
fi

echo "DONE"
