#!/bin/bash
JS_COMPRESSION_OPTS="dead-code=false,unsafe=false,unused=false"

check_lessc() {
    if type lessc &> /dev/null; then
        LESSC=lessc
    else
        if [ ! -f node_modules/.bin/lessc ]; then
            echo "Installing less"
            npm install less
        fi
        LESSC=node_modules/.bin/lessc
    fi
}

check_uglifyjs2() {
    if [ ! -f node_modules/.bin/uglifyjs2 ]; then
        echo "Installing uglify-js2"
        npm install uglify-js2
    fi
    UGLIFYJS2=node_modules/.bin/uglifyjs2
}


check_uglifycss() {
    if [ ! -f node_modules/.bin/uglifycss ]; then
        echo "Installing uglifycss"
        npm install uglifycss
    fi
    UGLIFYCSS=node_modules/.bin/uglifycss
}

# I should do this with a Makefile

if [ ! -f ../index.html -o ../bibliography.js -nt ../index.html -o $(find ../doc/ -name '*.txt' -newer ../index.html | wc -l) -gt 0 ]; then
    node lib/main.js
    echo "Generated HTML"
fi

if [ ! -f ../styles.css -o ! -f ../css/styles.css -o ../css/styles.less -nt ../styles.css ]; then
    check_lessc
    $LESSC -x ../css/styles.less > ../css/styles.css
    echo "Generated styles.css"
fi

if [ ! -f ../styles.css -o $(find ../css/ -name '*.css' -newer ../styles.css | wc -l) -gt 0 ]; then
    check_uglifycss
    $UGLIFYCSS ../css/{styles,keys,codemirror}.css > ../styles.css
    echo "Compressed CSS"
fi

if [ ! -f ../scripts.js -o $(find ../js/ -name '*.js' -newer ../scripts.js | wc -l) -gt 0 ]; then
    check_uglifyjs2
    $UGLIFYJS2 ../js/{codemirror,javascript,clike,scheme,parse-js,process,formatter}.js -o ../scripts.js -c $JS_COMPRESSION_OPTS
    echo "Compressed JS"
fi

echo "DONE"
